### ISSUE TITLE
File "c:/Users/awips/pysound.py", line 14, in <module>     from  . import paramsImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by Linuxuser1234** [irmen/synthesizer#19]

**Comment by Linuxuser1234** [comment]
here is line 14: from  . import params

**Comment by irmen** [comment]
There's no file pysound.py in this project and nowhere there is a line 14 like that.
Are you looking at the right code?
I think this doesn't belong here?

If the error is occuring in a file pysound.py that you wrote yourself, you're gonna have to fix that import yourself because you cannot import (sub)modules from a library like that.

**Comment by Linuxuser1234** [comment]
I created the pysound file but I imported your code to my file

**Comment by irmen** [comment]
please show us your source file and how you import.

**Comment by irmen** [comment]
This looks suspiciously like a generic Python package import error, rather than an issue with this library. Closing.
